function [dist] = distToTether(x,tl)
% x is the vector generated by NumericalTetherHopping
% tl is the vector of tether locations generated by NumericalTetherHopping
numSteps = size(x,1);
dist = zeros(1,numSteps);
for t=1:numSteps
    dist(t) = abs(x(t,1)-tl(x(t,2)));
end
end